name: Build

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    tags: [ v* ]
  pull_request:
  merge_group:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
          fetch-depth: 0

      - name: Write key
        if: ${{ ( github.event_name != 'pull_request' && github.ref == 'refs/heads/master' ) || github.ref_type == 'tag' }}
        run: |
          if [ ! -z "${{ secrets.KEY_STORE }}" ]; then
            echo storePassword='${{ secrets.KEY_STORE_PASSWORD }}' >> keystore.properties
            echo keyAlias='${{ secrets.ALIAS }}' >> keystore.properties
            echo keyPassword='${{ secrets.KEY_PASSWORD }}' >> keystore.properties
            echo storeFile=$PWD/'key.jks' >> keystore.properties
            echo '${{ secrets.KEY_STORE }}' | base64 --decode > key.jks
          fi

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: |
          ./gradlew assembleRelease

      - name: Upload release
        uses: actions/upload-artifact@v4
        with:
          name: "MyInjector"
          path: "./app/build/outputs/apk/release/*.apk"
          compression-level: 9

      - name: Upload mappings
        uses: actions/upload-artifact@v4
        with:
          name: "MyInjector-mapping"
          path: "./app/build/outputs/mapping/release"
          compression-level: 9

      - name: Post to channel
        if: github.ref == 'refs/heads/master'
        env:
          CHANNEL_ID: ${{ secrets.TELEGRAM_TO }}
          BOT_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          COMMIT_MESSAGE: |+
            New push to github\!
            ```
            ${{ github.event.head_commit.message }}
            ```by `${{ github.event.head_commit.author.name }}`
            See commit detail [here](${{ github.event.head_commit.url }})
            Snapshot apk is attached
        run: |
          if [ -z "$CHANNEL_ID" ] || [ -z "$BOT_TOKEN" ]; then
            exit 0
          fi
          FILE=app/build/outputs/apk/release/MyInjector-*.apk
          FILE=$(echo $FILE)
          NAME=${FILE%.apk}
          MAPPING=$(basename $NAME.mapping.zip)
          zip -9 -r -j $MAPPING ./app/build/outputs/mapping/release
          ESCAPED=`python3 -c 'import json,os,urllib.parse; print(urllib.parse.quote(json.dumps(os.environ["COMMIT_MESSAGE"])))'`
          curl -v "https://api.telegram.org/bot${BOT_TOKEN}/sendMediaGroup?chat_id=${CHANNEL_ID}&media=%5B%7B%22type%22%3A%22document%22%2C%20%22media%22%3A%22attach%3A%2F%2Frelease%22%7D%2C%7B%22type%22%3A%22document%22%2C%20%22media%22%3A%22attach%3A%2F%2Fmapping%22%2C%22parse_mode%22%3A%22MarkdownV2%22%2C%22caption%22%3A${ESCAPED}%7D%5D" -F release="@$FILE" -F mapping="@$MAPPING"
